# Generated by Django 5.1 on 2024-10-03 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run_pipeline', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='uploadprocess',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='uploadprocess',
            name='id',
        ),
        migrations.RemoveField(
            model_name='uploadprocess',
            name='output_files',
        ),
        migrations.RemoveField(
            model_name='uploadprocess',
            name='uploaded_files',
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='run_pipeline.uploadprocess'),
        ),
        migrations.AlterField(
            model_name='uploadprocess',
            name='process_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
